kind: pipeline
name: default
type: docker

steps:
  #  - name: package
  #    image: maven:3.6.3-jdk-11-slim
  #    commands:
  #      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - name: publish-release
    image: plugins/docker
    settings:
      registry: nexus:8123
      repo: nexus:8123/foo/bar
      dockerfile: src/main/docker/Dockerfile
      username: admin
      password: p123p123
      insecure: true
      auto_tag: true
    when:
      event:
        - tag

  - name: publish-latest
    image: plugins/docker
    settings:
      registry: nexus:8123
      repo: nexus:8123/foo/bar
      dockerfile: src/main/docker/Dockerfile
      username: admin
      password: p123p123
      insecure: true
      tags: latest
    when:
      event:
        - push
      branch:
        - master

  - name: publish-snapshot
    image: plugins/docker
    settings:
      registry: nexus:8123
      repo: nexus:8123/foo/bar
      dockerfile: src/main/docker/Dockerfile
      username: admin
      password: p123p123
      insecure: true
      tags: snapshot
    when:
      event:
        - push
      branch:
        - develop


trigger:
  event:
    - push
    - tag
    - pull_request