kind: pipeline
name: default
type: docker

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - ping 172.17.0.7:3000 -c 3
      - git clone http://172.17.0.7:3000/alex/code-with-quarkus.git .
      - git checkout $DRONE_COMMIT
  - name: package
    image: maven:3.6.3-jdk-11-slim
    commands:
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

trigger:
  branch:
    - master
  event:
    - push