kind: pipeline
name: default
type: docker

clone:
  disable: true

steps:
  - name: crawl
    image: ubuntu
    commands:
      - curl http://gitea:3000
  - name: clone
    image: alpine/git
    commands:
      - ping gitea -c 3
      - git clone http://gitea:30956/alex/code-with-quarkus.git .
      - git checkout $DRONE_COMMIT
  - name: package
    image: maven:3.6.3-jdk-11-slim
    commands:
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

trigger:
  branch:
    - master
  event:
    - push