version: '3'

services:
  drone-server:
    container_name: drone
    image: drone/drone:1.7.0
    ports:
      - 80:80
    environment:
      DRONE_OPEN: 'false'
      DRONE_HOST: 'http://drone'
      DRONE_ADMIN: 'alex'
      DRONE_GITEA: 'true'
      DRONE_GITEA_SERVER: 'http://gitea:3000'
      DRONE_GITEA_CLIENT_ID: 'bc396c1c-e5f6-4195-af69-b708c8b16402'
      DRONE_GITEA_CLIENT_SECRET: '7W-zYF1MlLLjuQJkR5CAnt9Z37fcE4kzWflsyuVA_Go='
      DRONE_RPC_SECRET: 'e47c15b45f85ae80ae039f8dfb1bd7e7'
      DRONE_SERVER_HOST: 'drone'
      DRONE_SERVER_PROTO: 'http'
      DRONE_LOGS_DEBUG: 'true'
      DRONE_LOGS_TEXT: 'true'
      DRONE_LOGS_PRETTY: 'true'
      DRONE_LOGS_COLOR: 'true'
      DRONE_RUNNER_NETWORKS: gitea_default
    networks:
      - drone-gitea_default

  drone-runner:
    container_name: runner
    image: drone/drone-runner-docker:1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: e47c15b45f85ae80ae039f8dfb1bd7e7
      DRONE_RUNNER_NAME: drone-1
      DRONE_RUNNER_NETWORKS: drone-gitea_default
    ports:
      - 3003:3000
    networks:
      - drone-gitea_default

networks:
  drone-gitea_default:
    external: true