version: '3'

services:
  drone-server:
    container_name: drone
    image: drone/drone:1.7.0
    ports:
      - 80:80
    environment:
      DRONE_OPEN: 'false'
      DRONE_HOST: 'http://drone'
      DRONE_ADMIN: 'alex'
      DRONE_GITEA: 'true'
      DRONE_GITEA_SERVER: 'http://gitea:3000'
      DRONE_GITEA_CLIENT_ID: '9e6e2910-2b3e-4389-8ce6-72000ae825d9'
      DRONE_GITEA_CLIENT_SECRET: 'zxW1CS69Y_jH8aJ0fPsl-4taMiNmp_acxKrg9C_TtOo='
      DRONE_RPC_SECRET: 'e47c15b45f85ae80ae039f8dfb1bd7e7'
      DRONE_SERVER_HOST: 'drone'
      DRONE_SERVER_PROTO: 'http'
      DRONE_LOGS_DEBUG: 'true'
      DRONE_LOGS_TEXT: 'true'
      DRONE_LOGS_PRETTY: 'true'
      DRONE_LOGS_COLOR: 'true'
      DRONE_RUNNER_NETWORKS: gitea_default
    networks:
      - gitea_default

  drone-runner:
    container_name: runner
    image: drone/drone-runner-docker:1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: e47c15b45f85ae80ae039f8dfb1bd7e7
      DRONE_RUNNER_NAME: drone-1
      DRONE_RUNNER_NETWORKS: gitea_default
    ports:
      - 3003:3000
    networks:
      - gitea_default

networks:
  gitea_default:
    external: true