version: '3'

services:
  drone-server:
    container_name: drone
    image: drone/drone:1.7.0
    ports:
      - 80:80
    environment:
      DRONE_OPEN: 'false'
      DRONE_HOST: 'http://drone'
      DRONE_ADMIN: 'alex'
      DRONE_GITEA: 'true'
      DRONE_GITEA_SERVER: 'http://172.21.0.4:3000'
      DRONE_GITEA_CLIENT_ID: 'a49cc1af-3497-469c-b036-b9975daf6ba5'
      DRONE_GITEA_CLIENT_SECRET: 'RBqqU4LXPHgYLPd-4smpERUGVGGR3ptjw47fzxkGyoU='
      DRONE_RPC_SECRET: 'e47c15b45f85ae80ae039f8dfb1bd7e7'
      DRONE_SERVER_HOST: 'drone'
      DRONE_SERVER_PROTO: 'http'
      DRONE_LOGS_DEBUG: 'true'

  drone-runner:
    container_name: runner
    image: drone/drone-runner-docker:1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: e47c15b45f85ae80ae039f8dfb1bd7e7
      DRONE_RUNNER_NAME: drone-1
    ports:
    - 3003:3000
