version: '3'

services:
  drone-server:
    container_name: drone
    image: drone/drone:1.7.0
    ports:
      - 80:80
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=https://drone.alex.com
      - DRONE_ADMIN=alex
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GITEA_CLIENT_ID=701ba6fa-12dd-4daa-a63c-7bff682ad37c
      - DRONE_GITEA_CLIENT_SECRET=YwKiGIfsnsI7Oh4hS4iWHA0utQnMZRNESbYrT0NvTD0=
      - DRONE_RPC_SECRET=e47c15b45f85ae80ae039f8dfb1bd7e7
      - DRONE_SERVER_HOST=drone.alex.com
      - DRONE_SERVER_PROTO=http
      - DRONE_GIT_ALWAYS_AUTH=false

  drone-runner:
    container_name: runner
    image: drone/drone-runner-docker:1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_HOST: drone
      DRONE_RPC_PROTO: http
      DRONE_RPC_SECRET: e47c15b45f85ae80ae039f8dfb1bd7e7
      DRONE_RUNNER_NAME: drone-1
    ports:
    - 3003:3000
