apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: drone-runner
  name: drone-runner
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3000
  selector:
    io.kompose.service: drone-runner
