apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: drone
  name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner
    spec:
      containers:
        - name: runner
          image: drone/drone-runner-kube:1.0.0-beta.2
          ports:
            - containerPort: 3000
          env:
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_RPC_HOST
              value: drone
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_RPC_SECRET
              value: e47c15b45f85ae80ae039f8dfb1bd7e7