apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: drone
  name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: drone
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: drone
    spec:
      containers:
        - env:
            - name: DRONE_ADMIN
              value: alex
            - name: DRONE_GITEA
              value: "true"
            - name: DRONE_GITEA_CLIENT_ID
              value: 5206d6db-bbe4-44cb-a53c-893fdc6df298
            - name: DRONE_GITEA_CLIENT_SECRET
              value: X-HLuaoKL3V1ALrH_73lqjI6BhtTTxXGDjqkFYVPkyw=
            - name: DRONE_GITEA_SERVER
              value: http://192.168.39.111:32016
            - name: DRONE_LOGS_DEBUG
              value: "true"
            - name: DRONE_OPEN
              value: "false"
            - name: DRONE_RPC_SECRET
              value: e47c15b45f85ae80ae039f8dfb1bd7e7
            - name: DRONE_SERVER_HOST
              value: 192.168.39.111:31540
            - name: DRONE_SERVER_PROTO
              value: http
          image: drone/drone:1.7.0
          imagePullPolicy: ""
          name: drone
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
