version: '3'
services:
  web:
    container_name: gitea
    image: gitea/gitea:1.12.4
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol: