apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "22"
      port: 22
      targetPort: 22
  selector:
    io.kompose.service: gitea
