apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: gitea
    spec:
      containers:
        - image: gitea/gitea:1.8.3
          imagePullPolicy: ""
          name: gitea
          ports:
            - containerPort: 3000
            - containerPort: 22
          resources: {}
      restartPolicy: Always
