version: '3'

services:
  drone-runner:
    container_name: nexus
    image: sonatype/nexus3:3.26.1
    ports:
      - 8081:8081
      - 8123:8123
    networks:
      - drone-gitea_default

networks:
  drone-gitea_default:
    external: true